### ISSUE TITLE
Tagged images

### ISSUE THREAD

**Issue by mausch** [ContinuumIO/docker-images#12]
At the moment https://hub.docker.com/r/continuumio/miniconda3/tags/ lists only a "3.9.0" tag (and obviously the "latest" tag).

I'm guessing that 3.9.0 tag is from https://github.com/ContinuumIO/docker-images/commit/c152ac0b928e0aab887e4b518f7780c9e4d49a3e , is there any reason why later images aren't tagged?

Cheers

**Comment by ianozsvald** [comment]
+1 for tagged images please

**Comment by mutirri** [comment]
Hi, 

First relase was performed manually, that's why `3.9.0` tag exists.
From some time now we are using automatic builds.
It is not possible in current implementation of Docker service to have 'tagged' images without additionall manual effort from our side. That generally breaks rule of having automated task.
When below proposition will be implemented, then we probably enable 'tagging' of our images.

https://github.com/docker/docker/issues/9561

Best.

**Comment by ianozsvald** [comment]
Doesn't that mean that until Docker Hub supports Tagging, nobody can use Anaconda Docker images for reproducible builds? Maybe it would be useful every month (or 2 or 3...) to publish tagged-builds, so people can make reproducible distributions?

**Comment by rgbkrk** [comment]
@mutirri Partial automation is better than no automation. Tagged builds give a lot of sanity to users who want to deploy resources reliably.

We're certainly tagging some of our images for ipython and jupyter:

![screenshot 2015-08-26 18 11 14](https://cloud.githubusercontent.com/assets/836375/9508726/c5133394-4c1d-11e5-8027-22adaa32e0f1.png)

We use branches above, but at the very least it's a lot better for people to rely on images if you give them something to pin to. If Continuum did this, we *too* would likely rely on them.

**Comment by mutirri** [comment]
Hi,

I talked to Crystal and we are considering some kind of constant tagging, probably up to next release.

**Comment by mausch** [comment]
Good news: docker hub will release dynamic matching of git branches and tags next week, which means there will be no need to go in and manually add each branch/tag into docker hub.
