### ISSUE TITLE
Inconsistent USER

### ISSUE THREAD

**Issue by OrangeDog** [ContinuumIO/docker-images#161]
I just noticed that miniconda3 runs as root for the Debian image, but a separate anaconda user for the Alpine image.

Any reason they can't all be root?

**Comment by OrangeDog** [comment]
Related: neither of them work if used with any other user (e.g. in a CI system) because /opt/conda/pkgs/urls.txt is not writable.

**Comment by soapy1** [comment]
There is a bit of history there. In an ideal world both images would use the anaconda user to avoid root. However, when we tried to make this change before we ended up breaking many users. ref https://github.com/ContinuumIO/docker-images/issues/120 and https://github.com/ContinuumIO/docker-images/issues/122. 
As a result we reverted our changes an brought back the debian based images. We still wanted to give users the ability to use a more modern/slim docker image, that is the new alpine image. 

If you use the users when running the images they should be working. If they are not please provide the steps to reproduce your issue

**Comment by OrangeDog** [comment]
I think it's harder to use when it's not defaulting to root, because you have to switch to root to install anything, and then back to the anaconda uid.

**Comment by Peque** [comment]
I agree; images should use a non-root user.

@soapy1 Would it be possible to reconsider this change for the Debian-based image too?

Alpine is not always an option for performance reasons. Conda is used in many data-intensive applications and, for those cases, Alpine is slower (uses musl instead of glibc).

Maybe it would be nice to push this change with the 4.8 Anaconda bump? :blush:
