### ISSUE TITLE
Documentation on docker tags?

### ISSUE THREAD

**Issue by finete** [ContinuumIO/docker-images#188]
I want to use the `docker-images/miniconda3/debian/Dockerfile` docker because it uses *DebianBuste-slim*,
However I couldn't find documentation  about which tag I should use from [DockerHub miniconda3 image](https://hub.docker.com/r/continuumio/miniconda3/tags).
Is the default one?

**Comment by MosheVai** [comment]
for anybody in the future currently its the default `FROM continuumio/miniconda3`  👀

**Comment by MosheVai** [comment]
According to the [Dokerfile](https://hub.docker.com/r/continuumio/miniconda3/dockerfile) on *dockerhub* *continuumio/miniconda3:latest* uses *debian:latest* and not *debian:buster-slim*

**Comment by dbast** [comment]
This got fixed by deriving the container tags from git tags via Github Actions, see https://github.com/ContinuumIO/docker-images/blob/master/.github/workflows/miniconda_debian_ci.yml ... currently continuumio/miniconda3:latest = continuumio/miniconda3:4.10.3p0 = https://github.com/ContinuumIO/docker-images/blob/miniconda3-v4.10.3p0/miniconda3/debian/Dockerfile
