### ISSUE TITLE
Please restore ssh to the continuumio/miniconda3 image

### ISSUE THREAD

**Issue by mivade** [ContinuumIO/docker-images#218]
It looks like a recent change to the `continuumio/miniconda3` image removed `ssh`. This breaks a lot of CI where cloning of other git repos happens over SSH. Example:

```
$ docker pull continuumio/miniconda3
Using default tag: latest
latest: Pulling from continuumio/miniconda3
b4d181a07f80: Already exists
4ebe3a5c6727: Pull complete
bd4723e13c8a: Pull complete
Digest: sha256:0ed0f871f40f6667e1a952e54dd674f3c2d767c2da14139e036d2b55e5647429
Status: Downloaded newer image for continuumio/miniconda3:latest
docker.io/continuumio/miniconda3:latest

$ docker run --rm -ti continuumio/miniconda3 /bin/bash
(base) root@6ad183109ee1:/# ssh
bash: ssh: command not found
```

Of course I can install `ssh` myself in my own Docker images that are based off of this, but is there a reason to exclude such a common tool?

**Comment by dbast** [comment]
@mivade Thanks for the quick report. Only the *latest* image does not have it, the tagged images still have it.

It was not intentional removed, but the `--no-install-recommends` was added to the apt-get call (as best practise, advised by hadolint) to lower the size of the image and instead explicitly install all required packages.

Will add `openssh-client` to fix that.

**Comment by mivade** [comment]
Thanks!
