### ISSUE TITLE
gcc does not work

### ISSUE THREAD

**Issue by bjodah** [ContinuumIO/docker-images#23]
This is quite broken:

``` Dockerfile
FROM continuumio/miniconda:3.19.0
ENV PATH /opt/miniconda2/bin:$PATH
RUN conda install conda-build gcc
```

```
...
Couldn't locate crtXXX.o in default library search paths. You may not have it  at all. It is usually packaged in libc6-dev/glibc-devel packages. We will try  to locate crtXXX.o with system installed gcc...
There is no /usr/bin/gcc
*** Can't install the gcc package unless your system has crtXXX.o. ***
conda-build-1. 100% |###############################| Time: 0:00:00 492.87 kB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
Error: Error: post-link failed for: gcc-4.8.5-3
```

**Comment by msarahan** [comment]
I recommend you try the conda_builder_linux image instead: https://github.com/ContinuumIO/docker-images/tree/master/conda_builder_linux

This image is built to build packages, and is based on CentOS5, rather than Debian, like the user-space images.  That old version of CentOS5 ensures that the packages you create are backwards compatible with most Linux platforms in use.

If you have questions or issues with using the conda_builder_linux image, please ping me.

**Comment by oroszgy** [comment]
`RUN apt-get install linux-headers-amd64 build-essentions ` worked for me.

**Comment by msarahan** [comment]
That will work, but the packages you produce will only be backwards compatible to Linux distributions that have glibc equal to or newer than 2.13.  The build image has backward compatibility to glibc 2.5. Also the build image offers gcc 5.2, which has better c++11 and c++14 support.

Also, you'll be building with the same tools that continuum uses, so you'll hopefully run into fewer unexpected build issues.

**Comment by bjodah** [comment]
@msarahan thanks!

I managed to incorporate conda_builder_linux in my build process:
https://github.com/chemreac/chemreac_anaconda

it looks like I will need to tweak some recipes, e.g. adding `$PREFIX/lib64` to `LIBRARY_PATH` and `LD_LIBRARY_PATH`. But overall it is looking good. Thank you for working on this!

**Comment by msarahan** [comment]
@bjodah nice work.  I'm a bit puzzled why you mount /opt, though.  Wouldn't it be sufficient to mount only the output folder(s):

-v /path/you/want/package/output/linux-64:/opt/miniconda/conda-bld/linux-64
-v /path/you/want/package/output/linux-32:/opt/miniconda/conda-bld/linux-32
-v /path/you/want/package/output/noarch:/opt/miniconda/conda-bld/noarch

should cover all the bases.  By mounting /opt, I worry that you're overwriting miniconda (maybe that's what you want, though?)

Also, I'm not sure why it's necessary to add those things to LIBRARY_PATH and LD_LIBRARY_PATH.  That mostly indicates something going wrong with the relocatability stuff in conda build.  I have observed recipes find old versions of system libraries in /usr/lib*, rather than /usr/local/lib*, where our custom GCC lives.  I think that should be fixed in the latest image - we now symlink stuff in /usr/lib* to stuff in /usr/local/lib*

Regardless, I'm happy you're finding value in it, and I welcome any suggestions or feedback you have.

**Comment by bjodah** [comment]
@msarahan I mount `/opt` out of convenience: allows me to re-use `miniconda/pkgs` between `docker run` invocations so that I don't have to download the same packages over and over again.

Also it makes it easier to inspect e.g. `miniconda/conda-bld/broken/` and `miniconda/envs/_test/`

If I mess something up I just delete my local `./opt/` folder and the state will be well defined again (makes a fresh copy from your docker image).

Regarding lib64 I needed to make sundials run_test.sh look like this:
```
#!/bin/sh
gcc -I${PREFIX}/include -L${PREFIX}/lib64 -L${PREFIX}/lib -o cvRoberts_dns cvRoberts_dns.c -lm -lsundials_cvode -llapack -lblas -lsundials_nvecserial
LD_LIBRARY_PATH=$PREFIX/lib64:$LD_LIBRARY_PATH ./cvRoberts_dns
```

the build script did not need any modifications:
```
#!/bin/sh
mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_BUILD_TYPE:STRING=Release -DBUILD_SHARED_LIBS:BOOL="1" -DBUILD_STATIC_LIBS:BOOL="0" -DEXAMPLES_ENABLE:BOOL="0" -DEXAMPLES_INSTALL:BOOL="0" -DLAPACK_ENABLE:BOOL="1" -DOPENMP_ENABLE:BOOL="0" ..
make install
```

**Comment by msarahan** [comment]
Ah, that makes more sense.  I suppose it also gives you better control over which version of conda, conda-build etc are in use.  Thanks for pointing out this workflow to me!

Do you have any idea which library sundials is missing if you don't add those flags?

The general way that CMake works with libraries is that there is a library finding script.  That script feeds in absolute paths to libraries, so that there is no ambiguity.  The fact that you're having to set those paths manually indicates that the CMake script for sundials might need improvement.  Also, the binaries you're producing there with your test don't have the rpath set.  In conda-build this happens at https://github.com/conda/conda-build/blob/a76769da0a6a0d9075ff92ed7c7a80641d57fbaa/conda_build/post.py#L269-L275

That tells the executable where to look for libraries, and is kind of like baking LD_LIBRARY_PATH into the executable.  You should prefer this approach to setting LD_LIBRARY_PATH - it is less likely to mess other things up.  However, it's totally fine to set LD_LIBRARY_PATH as you do for the test, as that is much simpler than figuring out that patchelf stuff.

**Comment by bjodah** [comment]
So it is the lapack shared libraries which end up in `lib64`. The recipe is from `conda-recipes`:
https://github.com/conda/conda-recipes/blob/master/lapack/build.sh

Am I allowed to link against MKL with my recipes? Then I could use that instead of netlib's reference lapack I suppose.

**Comment by msarahan** [comment]
AFAIK, yes.  It may impose some redistributability concerns from a licensing standpoint, but you'd have to read the MKL license to see how it might affect you.  See Intel's "nest" here: https://software.intel.com/sites/campaigns/nest/

So you can do whatever you want, it's only when you want to ship your packages or have someone use your recipes to ship packages that these things become a concern.

As for the technical aspect of using MKL, you could either take your (good) approach with mounting /opt, which makes your approach work, but not very portable, or you might want to layer it on top of conda_builder_linux in your own custom Dockerfile, which you could then share on Dockerhub, among others.

**Comment by bjodah** [comment]
@msarahan I see, I will look into the MKL licensing issues if I cannot make the reference lapack route work.

Actually I don't want to distribute the dockerimage, nor my mounted "./opt". I simply want to build the conda packages in a well defined environment, and then manually upload (using `anaconda upload ./opt/miniconda/conda-bld/linux-64/*.tar.bz2`) these to my repo on `anaconda.org` from where people may install them by adding my channel. Thanks to your work on setting the appropriate ABI this should work for most people, right?

Do you have any insight on why the lapack recipe causes the shared libraries to end up in `$PREFIX/lib64` instead of `$PREFIX/lib`, do you think it is a CentOS, CMake issue? or due to your patched version of gcc?

**Comment by msarahan** [comment]
OH!  Sorry, I missed that detail.  I'd consider that a "bug" of sorts in the lapack recipe.

The conda ecosystem operates under the assumption that only one CPU architecture can be operating under a given $PREFIX.  With that assumption, we keep the lib folder always named lib, no matter what the architecture is.  This is somewhat confusing, because it is different from how all of Linux does it.  Some Linux distributions (Ubuntu, I think) have 64-bit as /lib and 32-bit as lib32; others have lib and lib64.

I think the correct fix in this case is a change to the lapack recipe so that it always installs into $PREFIX/lib (or at least moves/copies lib64 into lib, if that's easier)

> Thanks to your work on setting the appropriate ABI this should work for most people, right?

I hope so!  Time will tell.  I have done the best I can, but there may be more to learn.

**Comment by dbast** [comment]
This was fixed by the referenced PR, thus closing. Please reopen, if this still is an issue.
