### ISSUE TITLE
continuumio/miniconda:4.7.12 container is broken

### ISSUE THREAD

**Issue by stevekm** [ContinuumIO/docker-images#267]
It is no longer possible to use the Docker container `continuumio/miniconda:4.7.12` as the base image for building your own container. 

Dockerfile:

```
FROM continuumio/miniconda:4.7.12
RUN apt-get update
```

building the container:

```
$ docker build -t "stevekm/myrepo:latest" .

Sending build context to Docker daemon  37.77MB
Step 1/11 : FROM continuumio/miniconda:4.7.12
 ---> b8ea69b5c41c
Step 2/11 : RUN apt-get update
 ---> Running in 179112b49589
Get:1 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:2 http://deb.debian.org/debian buster InRelease [122 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Reading package lists...
E: Repository 'http://security.debian.org/debian-security buster/updates InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
E: Repository 'http://deb.debian.org/debian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
E: Repository 'http://deb.debian.org/debian buster-updates InRelease' changed its 'Suite' value from 'stable-updates' to 'oldstable-updates'
The command '/bin/sh -c apt-get update' returned a non-zero code: 100
```

Looks like this is a thing that happened recently in the Debian  base image (as per threads [here](https://stackoverflow.com/questions/68802802/repository-http-security-debian-org-debian-security-buster-updates-inrelease) and [here](https://stackoverflow.com/questions/68787732/debian-11-update-broke-samueldebruyn-debian-git) ) but it is not clear to me what the correct solution is. As it stands, `continuumio/miniconda:4.7.12` is no longer useable.

**Comment by dbast** [comment]
continuumio/miniconda:4.7.12 is not broken. You can still use it to install packages via conda. What stopped working is `apt-get update` and `apt-get install`, because buster was renamed to old-stable (which happens outside of our control).

The failing command is: `docker run continuumio/miniconda:4.7.12 bash -l -c "apt-get update"``

The solution is: `docker run continuumio/miniconda:4.7.12 bash -l -c "apt-get --allow-releaseinfo-change update"` or add `--allow-releaseinfo-change` to your mentioned Dockerfile.
