### ISSUE TITLE
Re-order PATH?

### ISSUE THREAD

**Issue by kbeamnsidc** [ContinuumIO/docker-images#41]
Currently the Dockerfiles for miniconda prepend the conda bin directory to the `$PATH`:

`ENV PATH /opt/conda/bin:$PATH`

[miniconda](https://github.com/ContinuumIO/docker-images/blob/master/miniconda/Dockerfile)
[miniconda3](https://github.com/ContinuumIO/docker-images/blob/master/miniconda3/Dockerfile)

This causes problems if a conda package gets installed that has an executable that shadows an executable already in `/usr/bin`, for example. It seems like the conda directory should be placed after the `$PATH`. The default `$PATH` includes `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`.

Is there a reason for this ordering I'm not thinking of?

**Comment by dbast** [comment]
This is intentional and won't change due to the following reasoning: Users have full control on user space level (where conda lives), but less control on system level (like /usr/bin). If the user decides to install a tool with newer $version than the system provides, he then wants to have this with higher priority compared to the system provide one (he maybe cannot change the version of the tool on system level due to permissions).
