### ISSUE TITLE
Bump Python version on Docker Hub

### ISSUE THREAD

**Issue by NoctuaNivalis** [ContinuumIO/docker-images#50]
Could you bump the python version in the description on [the docker hub](https://hub.docker.com/r/continuumio/anaconda3/)? I wanted python 3.6 and I only noticed it was already updated when I came here.

**Comment by jontonsoup** [comment]
@NoctuaNivalis is the version on docker 3.6? I'm not seeing that for FROM continuumio/miniconda3

**Comment by mutirri** [comment]
The description was changed on Docker service.
Now it points to proper version of python - which is currently 3.6 for anaconda3.

**Comment by jontonsoup** [comment]
@mutirri do you mind answering my question about 3.5 vs 3.6? My miniconda is showing 3.5

**Comment by mutirri** [comment]
@jontonsoup yes, miniconda3 uses Python 3.5.2.
The docker image was created some time ago and was based on latest available version at that moment:
https://repo.continuum.io/miniconda/Miniconda2-4.2.12-Linux-x86_64.sh

I will upgrade the image to 4.3.11 soon (Python 3.6.0) soon.

**Comment by jontonsoup** [comment]
Thanks! 

On Tue, Feb 28, 2017 at 4:14 PM "Kamil Kwiek (irritum)"

<
mailto:
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

https://github.com/jontonsoup
yes, miniconda3 uses Python 3.5.2.

The docker image was created some time ago and was based on latest available version at that moment:
https://repo.continuum.io/miniconda/Miniconda2-4.2.12-Linux-x86_64.sh

I will upgrade the image to 4.3.11 soon (Python 3.6.0) soon.

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/ContinuumIO/docker-images/issues/50#issuecomment-283162412
, or

**Comment by jontonsoup** [comment]
@mutirri is there an open issue for this for me to follow?
