### ISSUE TITLE
anaconda 4.4.0 has incorrect python version

### ISSUE THREAD

**Issue by drorasaf** [ContinuumIO/docker-images#58]
I am using the anaconda3 docker. when trying to install python3.4, I get an error:
UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.4*
  - testpath -> python 2.7*
Use "conda info <package>" to see the dependencies for each package.

It seems like python 2 is used inside the docker

When I use anaconda 4.3.1 everything works fine

**Comment by dbast** [comment]
Recent Anaconda3 images have Python 3 installed, see e.g. `docker run -i -t continuumio/anaconda3 python --version`

Instead of installing a different Python version into the base environment (which can cause conflicts), creating a new environment is always an (better) option: `conda create --name myenv python==3.8 -y && conda activate myenv && python --version`
